# Trading.Log.Structure
# v2024.7

## Positions
+ Long
+ Short

## Status
+ Pending
+ Holding
+ Resolve
+ Intervene

## Asset - Prevent multi assets overtrade
+ classified by Currency group i.e. G1 EURUSD


# Execution
## HTF POI
+ i.e. 4H, D, W, M

## Entry
+ gray -- follow previous S.PD array
+ red -- entry at POI sting, expect reversal
+ purple -- after HTF POI bounce, expect reversal
+ green -- 2PD array bouce off of HTF POI
  
## Entry Type
+ Limit Entry
+ Mkt Entry

## Target
+ Liq x TF
+ FVG x TF

## ITR TF
+ 1H
+ 4H
+ D

## ITR Trend
+ Bullish
+ Bearish


## Overview
LONG | HOLDING | EURUSD | 4H.POI | gray -- follow previous S.PD array | Mkt Entry | M.$ | Bullish |



# Description on page
## Image
## Development
## Other Notes

# Notion formula/code
hour(parseDate(formatDate(prop("Time"), "YYYY-MM-DDTHH:mmZ")))