// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © TheAimLiu2
// @version=5

// Sections
// 0 Constants
// 1 Inputs
// 2 Functions
// 3 Calculation
// 4 Color Conditions
// 5 Plot
// 6 Debug/label

// -------------------------------- List bugs ----------------------------------s
// week and month error <= fixed switch case logic

// -----------------------------------------------------------------------------
//                                 0 Constant                                   
// -----------------------------------------------------------------------------
PRECISION_LIMIT = 6 // significant numbers

this_tf = timeframe.period
this_ticker = syminfo.tickerid
this_tz = syminfo.timezone

// ------------------------------ candle colors --------------------------------
var gold_color =#b59410

indicator("Fair Value Gap Highlight, 2024", shorttitle= "FVG,2024", overlay=true, precision=PRECISION_LIMIT)
// -----------------------------------------------------------------------------
//                                  1 inputs                                    
// -----------------------------------------------------------------------------

g1 = "hightlight colors"
tip12 = 'Auto bearish color'
bull_color = input.color(color.blue, title="Bull", group=g1, inline='l1g1')
bear_color = input.color(color.red, title="Bear", group=g1, inline='l1g1')
// auto_color = input.bool(true,title="Auto bear color", group=g1, inline='l1g1')

// thres = input.float(1.1,title="threshold",group=g1,inline="l2g1")
per = input.int(80,title="percentile",group=g1,inline="l3g1")
lookback = input.int(14,title="look back",group=g1,inline="l3g1")


// -----------------------------------------------------------------------------
//                                 2 Functions                                  
// -----------------------------------------------------------------------------
// --------------------------- fetch data from tf ------------------------------
// fetch data from selected tf
// fetch_tf(_sym, _res, _src) => 
//     request.security(_sym, _res, _src, lookahead = barmerge.lookahead_on)

// --------------------------- Hikin Aishi Candles -----------------------------
// fetch HK candles from ohlc on the tf

// ------------------------------- auto colors ---------------------------------
// auto bear highlight
// error
// auto_period_bear_color(str_tf)=>
//     _15m = 900
//     _1h = 3600  
//     _4h = 14400
//     _1d = 86400
//     _1w = 604800
//     _1M = 2628003
//     this_tf_second = timeframe.in_seconds(str_tf)
//     if this_tf_second <= _15m
//         [color.red,1]
//     else if this_tf_second > _15m and this_tf_second <= _1h
//         [#66bb6a,2] // lite lime
//     else if this_tf_second > _1h and this_tf_second <= _4h
//         [color.fuchsia,3]
//     else if this_tf_second > _4h and this_tf_second <= _1d
//         [color.new(gold_color,0),4]
//     else if this_tf_second > _1d and this_tf_second <= _1w
//         [color.blue,5]
//     else // ????  
//         [color.blue,9]
// --------------------- fetch hk candles with tf input ------------------------

// ---------------------------- generate hk bars -------------------------------

// -----------------------------------------------------------------------------
//                                3 Calculation                                 
// -----------------------------------------------------------------------------
// FVG must have 3 candle confirmation. Kernel = 3

ran = math.abs(close - open) //range
// pin_ran = math.abs(high - low) - math.abs(close - open) // pin range
// is_longstick = ran/pin_ran < thres
is_higher_than_percentile = ran[1] >= ta.percentile_linear_interpolation(ran,lookback,per)

// middle_bar_expansion = ran[2] < ran[1] and ran[1] > ran
middle_bar_bullish = close[1] - open[1] > 0
middle_bar_has_gap = middle_bar_bullish ? low > high[2] : low[2] > high

is_fvg = middle_bar_has_gap and is_higher_than_percentile
// -----------------------------------------------------------------------------
//                             4 Color Conditions                               
// -----------------------------------------------------------------------------
// [c,d] = auto_period_bear_color(this_tf)
// b_color = auto_color ? c : bear_color
b_color = bear_color
candle_color = middle_bar_bullish ? bull_color : b_color

// -----------------------------------------------------------------------------
//                                   5 plot                                     
// -----------------------------------------------------------------------------

barcolor(is_fvg ? candle_color : na , title="shave bar", offset=-1)
// plot(ran,title="range",display=display.status_line,color=candle_color)
// plot(pin_ran/ran,title="range",display=display.status_line,color=color.black)

// -----------------------------------------------------------------------------
//                              6 Debug Section                                 
// -----------------------------------------------------------------------------
// plotchar(is_fvg,title="debug", char="F",location=location.abovebar, offset=-1) // ok
// plot(d,title="debug2",color=candle_color,display=display.status_line)

// display status On the chart's last bar

// var label myLabel1 = na
// if last_bar_index == bar_index
    
//     label_msg = str.tostring(timeframe.in_seconds(this_tf) <= 604800)
//     myLabel1 := label.new(x=bar_index + 1, y=close, color=color.red, style=label.style_label_left, size=size.normal, tooltip=label_msg)
//     label.set_text(id=myLabel1, text=label_msg)



