// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © TheAimLiu2
// @version=5

// Sections
// 0 Constants
// 1 Inputs
// 2 Functions
// 3 Calculation
// 4 Color Conditions
// 5 Plot
// 6 Debug

// -----------------------------------------------------------------------------
//                                 0 Constant                                   
// -----------------------------------------------------------------------------
PRECISION_LIMIT = 6 // 6digits significant numbers
LINE_LIMIT = 50

chart_tf = timeframe.period
this_ticker_id = syminfo.tickerid
this_tz = syminfo.timezone

var divider_color = #2962ff // blue

indicator("Weekly divider 04-2024", shorttitle= "WD. 04-2024", overlay=true,precision=PRECISION_LIMIT, max_lines_count=LINE_LIMIT)
// -----------------------------------------------------------------------------
//                                  1 inputs                                    
// -----------------------------------------------------------------------------
div_color = input.color(color.new(divider_color,90), title="divider color")

show_debug = input.bool(false,title="Show Debug Value")
// -----------------------------------------------------------------------------
//                                 2 Functions                                  
// -----------------------------------------------------------------------------


// -----------------------------------------------------------------------------
//                                3 Calculation                                 
// -----------------------------------------------------------------------------
// Sat = 7, Sun = 1
is_starOfTheWeek = (dayofweek == dayofweek.monday or dayofweek == dayofweek.tuesday or dayofweek == dayofweek.wednesday)



// -----------------------------------------------------------------------------
//                             4 Color Conditions                               
// -----------------------------------------------------------------------------
conditions = is_starOfTheWeek and not is_starOfTheWeek[1] and not timeframe.ismonthly and not timeframe.isweekly
is_enteringNewWeek = conditions ? div_color : na

// -----------------------------------------------------------------------------
//                                   5 plot                                     
// -----------------------------------------------------------------------------
bgcolor(is_enteringNewWeek, title="New Week Color")

// -----------------------------------------------------------------------------
//                              6 Debug Section                                 
// -----------------------------------------------------------------------------
// display status On the chart's last bar
if barstate.islast and show_debug
    debug_msg = "debug val"+  str.tostring(dayofweek)
    myLabel = label.new(x=bar_index + 10, y=close, color=color.red, style=label.style_label_left, size=size.normal)
    label.set_text(id=myLabel, text=debug_msg)